# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20180609_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarditerm',
            name='award_id',
        ),
        migrations.RemoveField(
            model_name='awardsort',
            name='award_id',
        ),
        migrations.AlterField(
            model_name='awarditerm',
            name='award_sort_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.AwardSort', verbose_name='关联的奖项id'),
        ),
        migrations.AlterField(
            model_name='awarditerm',
            name='golden_spider_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.GoldenSpiderAward', verbose_name='关联的金蜘蛛奖id'),
        ),
        migrations.AlterField(
            model_name='goldenspideraward',
            name='intro',
            field=models.CharField(max_length=5000, verbose_name='奖项介绍'),
        ),
    ]
